### ISSUE TITLE
Alphanumeric input crashes on Version 8

### ISSUE THREAD

**Issue by grantdelacampa** [grantdelacampa/QR_JS#22]
Input size: 213
 Capacity arry: [8, 221]
version 8, 
mode ind: 0010
errCorrInfo: [54, 22, 2, 38, 2, 39, 154]
total bits 432
current binary length: 1185

ncaught RangeError: Invalid count value: -753
    at String.repeat (<anonymous>)
    at padBitsEnd (HelperFunctions.js:25:1)
    at fitTotalBits (DataEncoding.js:31:1)
    at generate (App.js:81:1)
    at handleClick (App.js:99:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)

**Comment by grantdelacampa** [comment]
I hit the lottery and was using the QR code version and error correction level that happened to have a bad value in the error correction info table: 
Should have been: '8-M': [**154**, 22, 2, 38, 2, 39, 154],
Was: '8-M': [**54**, 22, 2, 38, 2, 39, 154],
